name: miletrack
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  gsheets: ^0.4.2
  hexcolor: ^3.0.1
  dropdown_search: ^3.0.1
  firebase_core: ^2.8.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  file_picker: ^5.2.6
  firebase_storage: ^11.0.16
  flutter_pdfview: ^1.2.9
  path_provider: ^2.0.13
  http: ^0.13.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

